/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e_vote;

/**
 *
 * @author Hugod
 */
public class AdminMain extends javax.swing.JFrame {

    
    
    
    /**
     * Creates new form AdminMain
     */
    public AdminMain() {
        initComponents();
    }
   // VoteMain vm = new VoteMain();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRs = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Can1Rs = new javax.swing.JRadioButton();
        Can2Rs = new javax.swing.JRadioButton();
        Can3Rs = new javax.swing.JRadioButton();
        getRes = new javax.swing.JButton();
        ResultField = new javax.swing.JTextField();
        Can4Rs = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), new java.awt.Color(51, 153, 255), new java.awt.Color(51, 153, 255), new java.awt.Color(51, 153, 255)));
        jPanel1.setForeground(new java.awt.Color(51, 153, 255));

        buttonGroupRs.add(Can1Rs);
        Can1Rs.setText("Samuel");
        Can1Rs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Can1RsActionPerformed(evt);
            }
        });

        buttonGroupRs.add(Can2Rs);
        Can2Rs.setText("James");

        buttonGroupRs.add(Can3Rs);
        Can3Rs.setText("David");

        getRes.setBackground(new java.awt.Color(153, 255, 255));
        getRes.setForeground(new java.awt.Color(51, 102, 255));
        getRes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 255, 255), null, null));
        getRes.setBorderPainted(false);
        getRes.setLabel("RESULTS");
        getRes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getResMouseClicked(evt);
            }
        });
        getRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getResActionPerformed(evt);
            }
        });

        buttonGroupRs.add(Can4Rs);
        Can4Rs.setText("Maxwell");

        jLabel1.setText("ADMINISTRATOR PAGE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Can1Rs)
                            .addComponent(Can2Rs))
                        .addGap(163, 163, 163)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Can4Rs)
                            .addComponent(Can3Rs))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(ResultField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(getRes, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Can3Rs)
                    .addComponent(Can1Rs))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Can2Rs)
                    .addComponent(Can4Rs))
                .addGap(44, 44, 44)
                .addComponent(ResultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(getRes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Can1RsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Can1RsActionPerformed
        // TODO add your handling code here:
        
      //  vm.Cand1.getText();
        //System.out.print(vm.Cand1.getText());
    }//GEN-LAST:event_Can1RsActionPerformed

    private void getResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getResActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
    }//GEN-LAST:event_getResActionPerformed

    private void getResMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getResMouseClicked
        // TODO add your handling code here:
        if(Can1Rs.isSelected())
        { 
        // ResultField.setText("You select " +Can1Rs.getText());
           IO.Read1();
           int val = IO.value - 1;
            
           ResultField.setText(Can1Rs.getText() + " has : " + val + " votes");
        
        }
        
        else if(Can2Rs.isSelected())
        { 
        // ResultField.setText("You select " +Can1Rs.getText());
           IO.Read2();
           int val = IO.value - 1;
            
           ResultField.setText(Can2Rs.getText() + " has : " + val + "votes");
        
        }
        
        else if(Can3Rs.isSelected())
        { 
        // ResultField.setText("You select " +Can1Rs.getText());
           IO.Read3();
           int val = IO.value - 1;
            
           ResultField.setText(Can3Rs.getText() + " has : " + val + " votes");
        
        }
        
        else if(Can4Rs.isSelected())
        { 
        // ResultField.setText("You select " +Can1Rs.getText());
           IO.Read4();
           int val = IO.value - 1;
            
           ResultField.setText(Can4Rs.getText() + " has : " + val + " votes");
        
        }
        
    }//GEN-LAST:event_getResMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Can1Rs;
    private javax.swing.JRadioButton Can2Rs;
    private javax.swing.JRadioButton Can3Rs;
    private javax.swing.JRadioButton Can4Rs;
    private javax.swing.JTextField ResultField;
    private javax.swing.ButtonGroup buttonGroupRs;
    private javax.swing.JButton getRes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
